$(document).ready(function(){
  $("#panel").slideUp();
  $(".sumir").hide();    
  $(".menuLink").hide();    
  $(".iconMenuHide").show();      
  $(".menuIcon").show();
  $(".itemMenu").css("padding-left","0");
  $(".itemMenu").css("justify-content","center");
  $(".menu").css("transform","rotateX(0deg)");
  $(".menu").css("width","4vw");
  $(".menu").css("width","4vw");
  $(".cardArea").css("margin-left","6vw");  
    $("#menuIcon").click(function(){
      $(".sumir").hide();    
      $(".menuLink").hide();    
      $(".iconMenuHide").show();      
      $(".menuIcon").show();
      $(".itemMenu").css("padding-left","0");
      $(".itemMenu").css("justify-content","center");
      $(".menu").css("transform","rotateX(0deg)");
      $(".menu").css("width","4vw");
      $(".cardArea").css("margin-left","6vw"); 
    }); 
    $(".iconMenuHide").click(function(){
      $(".sumir").show();    
      $(".menuLink").show();      
      $(".iconMenuHide").hide();      
      $(".itemMenu").css("padding-left","10px");
      $(".itemMenu").css("justify-content","unset");
      $(".menu").css("transform","rotateX(0deg)");
      $(".menu").css("width","10vw");
      $("#center").css("justify-content","center");
      $("#center").css("padding-left","0px");
      $(".cardArea").css("margin-left","15vw");  
    });    
    $("#show").click(function(){
      $("p").show();
    });
    $("#flip").click(function(){
      $("#panel").slideToggle("slow");
    });  
  });